name: Main CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: create env file
        run: |
          cat < EOF > .env
          BASE_URL="/"
          VUE_APP_ENV_KAKAO_SDK_API_KEY=${{ secrets.VUE_APP_ENV_KAKAO_SDK_API_KEY }}
          VUE_APP_ENV_GOOGLE_CLIENT_ID=${{ secrets.VUE_APP_ENV_GOOGLE_CLIENT_ID }}
          VUE_APP_ENV_GOOGLE_CLIENT_SECRET=${{ secrets.VUE_APP_ENV_GOOGLE_CLIENT_SECRET }}
          VUE_APP_ENV_KAKAO_CLIENT_ID=${{ secrets.VUE_APP_ENV_KAKAO_CLIENT_ID }}
          VUE_APP_ENV_KAKAO_SECRET_KEY=${{ secrets.VUE_APP_ENV_KAKAO_SECRET_KEY }}
          EOF

      - name: build
        run: npm run build

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '${{secrets.ACCESS_KEY_ID}}'
          AWS_SECRET_ACCESS_KEY: '${{secrets.SECRET_ACCESS_KEY}}'
        run: |
          aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          dist s3://myxercisebucket